stages:
  - test

tets_codingstyle:
  stage: test
  tags:
    - php
  except:
    - master
  script:
    - composer install --quiet --no-interaction -- no-script
    - bin/php-cs-fixer fix --dry-run --using-cache=no --no-interaction --config=.php_cs -v